[package]
name = "sal"
version = "0.1.0"
edition = "2021"
authors = ["tim@welchnet.org"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
